server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  #consul注册中心地址
  cloud:
    consul:
      host: http://192.168.91.130
      port: 8599
      discovery:
        service-name: ${spring.application.name}