server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  #consul注册中心地址
  cloud:
    consul:
      host: http://192.168.91.130
      port: 8599
      discovery:
        service-name: ${spring.application.name}